#ifndef JNI_FFMPEG/ANDROID/ARMEABI-V7A/AVUTIL/FFVERSION_H
#define JNI_FFMPEG/ANDROID/ARMEABI-V7A/AVUTIL/FFVERSION_H
#define FFMPEG_VERSION "2.5.9"
#endif /* JNI_FFMPEG/ANDROID/ARMEABI-V7A/AVUTIL/FFVERSION_H */
